server:
  port: ":8080"

routes:
  upload_dir                        : "./folder"
  upload_path                       : "/upload"
  download_path                     : "/download"
  file_move_path                    : "/move"
  file_delete_path                  : "/delete"
  create_folder_path                : "/create_folder"
  upload_folder_path                : "/upload_folder"
  download_folder_path              : "/download_folder"
  query_folder_structure_path       : "/query_folder_structure"
  test: "/test"
